//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.28 at 10:52:32 PM ALMT 
//


package org.processbase.ui.core.bonita.forms;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Activities complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Activities">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="activity" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="pageflow" type="{}PageFlow" minOccurs="0"/>
 *                   &lt;element name="view-pageflow" type="{}ViewPageFlow" minOccurs="0"/>
 *                 &lt;/all>
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Activities", propOrder = {
    "activities"
})
public class Activities {

    @XmlElement(name = "activity")
    protected List<Activities.Activity> activities;

    /**
     * Gets the value of the activities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Activities.Activity }
     * 
     * 
     */
    public List<Activities.Activity> getActivities() {
        if (activities == null) {
            activities = new ArrayList<Activities.Activity>();
        }
        return this.activities;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="pageflow" type="{}PageFlow" minOccurs="0"/>
     *         &lt;element name="view-pageflow" type="{}ViewPageFlow" minOccurs="0"/>
     *       &lt;/all>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Activity {

        protected PageFlow pageflow;
        @XmlElement(name = "view-pageflow")
        protected ViewPageFlow viewPageflow;
        @XmlAttribute(name = "name", required = true)
        protected String name;

        /**
         * Gets the value of the pageflow property.
         * 
         * @return
         *     possible object is
         *     {@link PageFlow }
         *     
         */
        public PageFlow getPageflow() {
            return pageflow;
        }

        /**
         * Sets the value of the pageflow property.
         * 
         * @param value
         *     allowed object is
         *     {@link PageFlow }
         *     
         */
        public void setPageflow(PageFlow value) {
            this.pageflow = value;
        }

        /**
         * Gets the value of the viewPageflow property.
         * 
         * @return
         *     possible object is
         *     {@link ViewPageFlow }
         *     
         */
        public ViewPageFlow getViewPageflow() {
            return viewPageflow;
        }

        /**
         * Sets the value of the viewPageflow property.
         * 
         * @param value
         *     allowed object is
         *     {@link ViewPageFlow }
         *     
         */
        public void setViewPageflow(ViewPageFlow value) {
            this.viewPageflow = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
