//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.28 at 10:52:32 PM ALMT 
//


package org.processbase.ui.core.bonita.forms;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Actions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Actions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="action" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="variable" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="attachment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="variable-type" type="{}VariableType" minOccurs="0"/>
 *                   &lt;element name="expression" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="submit-button" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="connector" type="{}Connector" minOccurs="0"/>
 *                 &lt;/all>
 *                 &lt;attribute name="type" use="required" type="{}ActionType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Actions", propOrder = {
    "actions"
})
public class Actions {

    @XmlElement(name = "action")
    protected List<Actions.Action> actions;

    /**
     * Gets the value of the actions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Actions.Action }
     * 
     * 
     */
    public List<Actions.Action> getActions() {
        if (actions == null) {
            actions = new ArrayList<Actions.Action>();
        }
        return this.actions;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="variable" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="attachment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="variable-type" type="{}VariableType" minOccurs="0"/>
     *         &lt;element name="expression" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="submit-button" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="connector" type="{}Connector" minOccurs="0"/>
     *       &lt;/all>
     *       &lt;attribute name="type" use="required" type="{}ActionType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Action {

        protected String variable;
        protected String attachment;
        @XmlElement(name = "variable-type")
        protected VariableType variableType;
        protected String expression;
        @XmlElement(name = "submit-button")
        protected String submitButton;
        protected Connector connector;
        @XmlAttribute(name = "type", required = true)
        protected ActionType type;

        /**
         * Gets the value of the variable property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVariable() {
            return variable;
        }

        /**
         * Sets the value of the variable property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVariable(String value) {
            this.variable = value;
        }

        /**
         * Gets the value of the attachment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttachment() {
            return attachment;
        }

        /**
         * Sets the value of the attachment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttachment(String value) {
            this.attachment = value;
        }

        /**
         * Gets the value of the variableType property.
         * 
         * @return
         *     possible object is
         *     {@link VariableType }
         *     
         */
        public VariableType getVariableType() {
            return variableType;
        }

        /**
         * Sets the value of the variableType property.
         * 
         * @param value
         *     allowed object is
         *     {@link VariableType }
         *     
         */
        public void setVariableType(VariableType value) {
            this.variableType = value;
        }

        /**
         * Gets the value of the expression property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExpression() {
            return expression;
        }

        /**
         * Sets the value of the expression property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExpression(String value) {
            this.expression = value;
        }

        /**
         * Gets the value of the submitButton property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubmitButton() {
            return submitButton;
        }

        /**
         * Sets the value of the submitButton property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubmitButton(String value) {
            this.submitButton = value;
        }

        /**
         * Gets the value of the connector property.
         * 
         * @return
         *     possible object is
         *     {@link Connector }
         *     
         */
        public Connector getConnector() {
            return connector;
        }

        /**
         * Sets the value of the connector property.
         * 
         * @param value
         *     allowed object is
         *     {@link Connector }
         *     
         */
        public void setConnector(Connector value) {
            this.connector = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link ActionType }
         *     
         */
        public ActionType getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link ActionType }
         *     
         */
        public void setType(ActionType value) {
            this.type = value;
        }

    }

}
