//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.28 at 10:52:32 PM ALMT 
//


package org.processbase.ui.core.bonita.forms;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FormsDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FormsDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="welcome-page" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="external-welcome-page" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="process" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="process-label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="process-template" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="mandatory-symbol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="mandatory-label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="mandatory-style" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="error-template" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="pageflow" type="{}PageFlow" minOccurs="0"/>
 *                   &lt;element name="view-pageflow" type="{}ViewPageFlow" minOccurs="0"/>
 *                   &lt;element name="recap-pageflow" type="{}RecapPageFlow" minOccurs="0"/>
 *                   &lt;element name="activities" type="{}Activities" minOccurs="0"/>
 *                 &lt;/all>
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="product-version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormsDefinition", propOrder = {
    "welcomePage",
    "externalWelcomePage",
    "processes"
})
@XmlRootElement(name = "forms-definition")
public class FormsDefinition {

    @XmlElement(name = "welcome-page")
    protected String welcomePage;
    @XmlElement(name = "external-welcome-page")
    protected String externalWelcomePage;
    @XmlElement(name = "process")
    protected List<FormsDefinition.Process> processes;
    @XmlAttribute(name = "product-version")
    protected String productVersion;

    /**
     * Gets the value of the welcomePage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWelcomePage() {
        return welcomePage;
    }

    /**
     * Sets the value of the welcomePage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWelcomePage(String value) {
        this.welcomePage = value;
    }

    /**
     * Gets the value of the externalWelcomePage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalWelcomePage() {
        return externalWelcomePage;
    }

    /**
     * Sets the value of the externalWelcomePage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalWelcomePage(String value) {
        this.externalWelcomePage = value;
    }

    /**
     * Gets the value of the processes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcesses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormsDefinition.Process }
     * 
     * 
     */
    public List<FormsDefinition.Process> getProcesses() {
        if (processes == null) {
            processes = new ArrayList<FormsDefinition.Process>();
        }
        return this.processes;
    }

    /**
     * Gets the value of the productVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductVersion() {
        return productVersion;
    }

    /**
     * Sets the value of the productVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductVersion(String value) {
        this.productVersion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="process-label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="process-template" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="mandatory-symbol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="mandatory-label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="mandatory-style" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="error-template" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pageflow" type="{}PageFlow" minOccurs="0"/>
     *         &lt;element name="view-pageflow" type="{}ViewPageFlow" minOccurs="0"/>
     *         &lt;element name="recap-pageflow" type="{}RecapPageFlow" minOccurs="0"/>
     *         &lt;element name="activities" type="{}Activities" minOccurs="0"/>
     *       &lt;/all>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Process {

        @XmlElement(name = "process-label", required = true)
        protected String processLabel;
        @XmlElement(name = "process-template")
        protected String processTemplate;
        @XmlElement(name = "mandatory-symbol")
        protected String mandatorySymbol;
        @XmlElement(name = "mandatory-label")
        protected String mandatoryLabel;
        @XmlElement(name = "mandatory-style")
        protected String mandatoryStyle;
        @XmlElement(name = "error-template")
        protected String errorTemplate;
        protected PageFlow pageflow;
        @XmlElement(name = "view-pageflow")
        protected ViewPageFlow viewPageflow;
        @XmlElement(name = "recap-pageflow")
        protected RecapPageFlow recapPageflow;
        protected Activities activities;
        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "version", required = true)
        protected String version;

        /**
         * Gets the value of the processLabel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProcessLabel() {
            return processLabel;
        }

        /**
         * Sets the value of the processLabel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProcessLabel(String value) {
            this.processLabel = value;
        }

        /**
         * Gets the value of the processTemplate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProcessTemplate() {
            return processTemplate;
        }

        /**
         * Sets the value of the processTemplate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProcessTemplate(String value) {
            this.processTemplate = value;
        }

        /**
         * Gets the value of the mandatorySymbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMandatorySymbol() {
            return mandatorySymbol;
        }

        /**
         * Sets the value of the mandatorySymbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMandatorySymbol(String value) {
            this.mandatorySymbol = value;
        }

        /**
         * Gets the value of the mandatoryLabel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMandatoryLabel() {
            return mandatoryLabel;
        }

        /**
         * Sets the value of the mandatoryLabel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMandatoryLabel(String value) {
            this.mandatoryLabel = value;
        }

        /**
         * Gets the value of the mandatoryStyle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMandatoryStyle() {
            return mandatoryStyle;
        }

        /**
         * Sets the value of the mandatoryStyle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMandatoryStyle(String value) {
            this.mandatoryStyle = value;
        }

        /**
         * Gets the value of the errorTemplate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErrorTemplate() {
            return errorTemplate;
        }

        /**
         * Sets the value of the errorTemplate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErrorTemplate(String value) {
            this.errorTemplate = value;
        }

        /**
         * Gets the value of the pageflow property.
         * 
         * @return
         *     possible object is
         *     {@link PageFlow }
         *     
         */
        public PageFlow getPageflow() {
            return pageflow;
        }

        /**
         * Sets the value of the pageflow property.
         * 
         * @param value
         *     allowed object is
         *     {@link PageFlow }
         *     
         */
        public void setPageflow(PageFlow value) {
            this.pageflow = value;
        }

        /**
         * Gets the value of the viewPageflow property.
         * 
         * @return
         *     possible object is
         *     {@link ViewPageFlow }
         *     
         */
        public ViewPageFlow getViewPageflow() {
            return viewPageflow;
        }

        /**
         * Sets the value of the viewPageflow property.
         * 
         * @param value
         *     allowed object is
         *     {@link ViewPageFlow }
         *     
         */
        public void setViewPageflow(ViewPageFlow value) {
            this.viewPageflow = value;
        }

        /**
         * Gets the value of the recapPageflow property.
         * 
         * @return
         *     possible object is
         *     {@link RecapPageFlow }
         *     
         */
        public RecapPageFlow getRecapPageflow() {
            return recapPageflow;
        }

        /**
         * Sets the value of the recapPageflow property.
         * 
         * @param value
         *     allowed object is
         *     {@link RecapPageFlow }
         *     
         */
        public void setRecapPageflow(RecapPageFlow value) {
            this.recapPageflow = value;
        }

        /**
         * Gets the value of the activities property.
         * 
         * @return
         *     possible object is
         *     {@link Activities }
         *     
         */
        public Activities getActivities() {
            return activities;
        }

        /**
         * Sets the value of the activities property.
         * 
         * @param value
         *     allowed object is
         *     {@link Activities }
         *     
         */
        public void setActivities(Activities value) {
            this.activities = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

    }

}
