//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.28 at 10:52:32 PM ALMT 
//


package org.processbase.ui.core.bonita.forms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HeadingsPositions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HeadingsPositions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="left-headings" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="top-headings" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="right-headings" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="bottom-headings" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeadingsPositions", propOrder = {

})
public class HeadingsPositions {

    @XmlElement(name = "left-headings")
    protected boolean leftHeadings;
    @XmlElement(name = "top-headings")
    protected boolean topHeadings;
    @XmlElement(name = "right-headings")
    protected boolean rightHeadings;
    @XmlElement(name = "bottom-headings")
    protected boolean bottomHeadings;

    /**
     * Gets the value of the leftHeadings property.
     * 
     */
    public boolean isLeftHeadings() {
        return leftHeadings;
    }

    /**
     * Sets the value of the leftHeadings property.
     * 
     */
    public void setLeftHeadings(boolean value) {
        this.leftHeadings = value;
    }

    /**
     * Gets the value of the topHeadings property.
     * 
     */
    public boolean isTopHeadings() {
        return topHeadings;
    }

    /**
     * Sets the value of the topHeadings property.
     * 
     */
    public void setTopHeadings(boolean value) {
        this.topHeadings = value;
    }

    /**
     * Gets the value of the rightHeadings property.
     * 
     */
    public boolean isRightHeadings() {
        return rightHeadings;
    }

    /**
     * Sets the value of the rightHeadings property.
     * 
     */
    public void setRightHeadings(boolean value) {
        this.rightHeadings = value;
    }

    /**
     * Gets the value of the bottomHeadings property.
     * 
     */
    public boolean isBottomHeadings() {
        return bottomHeadings;
    }

    /**
     * Sets the value of the bottomHeadings property.
     * 
     */
    public void setBottomHeadings(boolean value) {
        this.bottomHeadings = value;
    }

}
