//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.28 at 10:52:32 PM ALMT 
//


package org.processbase.ui.core.bonita.forms;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.processbase.ui.core.bonita.forms package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.processbase.ui.core.bonita.forms
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HTMLAttributes.HtmlAttribute }
     * 
     */
    public HTMLAttributes.HtmlAttribute createHTMLAttributesHtmlAttribute() {
        return new HTMLAttributes.HtmlAttribute();
    }

    /**
     * Create an instance of {@link ColumnsStyles.ColumnStyle }
     * 
     */
    public ColumnsStyles.ColumnStyle createColumnsStylesColumnStyle() {
        return new ColumnsStyles.ColumnStyle();
    }

    /**
     * Create an instance of {@link RecapPageFlow }
     * 
     */
    public RecapPageFlow createRecapPageFlow() {
        return new RecapPageFlow();
    }

    /**
     * Create an instance of {@link Validators }
     * 
     */
    public Validators createValidators() {
        return new Validators();
    }

    /**
     * Create an instance of {@link Dependencies }
     * 
     */
    public Dependencies createDependencies() {
        return new Dependencies();
    }

    /**
     * Create an instance of {@link FieldValue }
     * 
     */
    public FieldValue createFieldValue() {
        return new FieldValue();
    }

    /**
     * Create an instance of {@link FormsDefinition }
     * 
     */
    public FormsDefinition createFormsDefinition() {
        return new FormsDefinition();
    }

    /**
     * Create an instance of {@link RowsStyles.RowStyle }
     * 
     */
    public RowsStyles.RowStyle createRowsStylesRowStyle() {
        return new RowsStyles.RowStyle();
    }

    /**
     * Create an instance of {@link Activities.Activity }
     * 
     */
    public Activities.Activity createActivitiesActivity() {
        return new Activities.Activity();
    }

    /**
     * Create an instance of {@link ValuesList }
     * 
     */
    public ValuesList createValuesList() {
        return new ValuesList();
    }

    /**
     * Create an instance of {@link PageFlow.Pages }
     * 
     */
    public PageFlow.Pages createPageFlowPages() {
        return new PageFlow.Pages();
    }

    /**
     * Create an instance of {@link ViewPageFlow.ViewPages }
     * 
     */
    public ViewPageFlow.ViewPages createViewPageFlowViewPages() {
        return new ViewPageFlow.ViewPages();
    }

    /**
     * Create an instance of {@link Connectors }
     * 
     */
    public Connectors createConnectors() {
        return new Connectors();
    }

    /**
     * Create an instance of {@link Actions }
     * 
     */
    public Actions createActions() {
        return new Actions();
    }

    /**
     * Create an instance of {@link Connector.InputParameters }
     * 
     */
    public Connector.InputParameters createConnectorInputParameters() {
        return new Connector.InputParameters();
    }

    /**
     * Create an instance of {@link PageFlow }
     * 
     */
    public PageFlow createPageFlow() {
        return new PageFlow();
    }

    /**
     * Create an instance of {@link Widgets }
     * 
     */
    public Widgets createWidgets() {
        return new Widgets();
    }

    /**
     * Create an instance of {@link Activities }
     * 
     */
    public Activities createActivities() {
        return new Activities();
    }

    /**
     * Create an instance of {@link FormsDefinition.Process }
     * 
     */
    public FormsDefinition.Process createFormsDefinitionProcess() {
        return new FormsDefinition.Process();
    }

    /**
     * Create an instance of {@link RecapPageFlow.RecapPages }
     * 
     */
    public RecapPageFlow.RecapPages createRecapPageFlowRecapPages() {
        return new RecapPageFlow.RecapPages();
    }

    /**
     * Create an instance of {@link ViewPageFlow }
     * 
     */
    public ViewPageFlow createViewPageFlow() {
        return new ViewPageFlow();
    }

    /**
     * Create an instance of {@link AvailableValues }
     * 
     */
    public AvailableValues createAvailableValues() {
        return new AvailableValues();
    }

    /**
     * Create an instance of {@link RedirectionURL }
     * 
     */
    public RedirectionURL createRedirectionURL() {
        return new RedirectionURL();
    }

    /**
     * Create an instance of {@link ViewPageFlow.ViewPages.ViewPage }
     * 
     */
    public ViewPageFlow.ViewPages.ViewPage createViewPageFlowViewPagesViewPage() {
        return new ViewPageFlow.ViewPages.ViewPage();
    }

    /**
     * Create an instance of {@link PageFlow.Pages.Page }
     * 
     */
    public PageFlow.Pages.Page createPageFlowPagesPage() {
        return new PageFlow.Pages.Page();
    }

    /**
     * Create an instance of {@link HTMLAttributes }
     * 
     */
    public HTMLAttributes createHTMLAttributes() {
        return new HTMLAttributes();
    }

    /**
     * Create an instance of {@link RecapPageFlow.RecapPages.RecapPage }
     * 
     */
    public RecapPageFlow.RecapPages.RecapPage createRecapPageFlowRecapPagesRecapPage() {
        return new RecapPageFlow.RecapPages.RecapPage();
    }

    /**
     * Create an instance of {@link ValuesList.AvailableValue }
     * 
     */
    public ValuesList.AvailableValue createValuesListAvailableValue() {
        return new ValuesList.AvailableValue();
    }

    /**
     * Create an instance of {@link RowsStyles }
     * 
     */
    public RowsStyles createRowsStyles() {
        return new RowsStyles();
    }

    /**
     * Create an instance of {@link Widget }
     * 
     */
    public Widget createWidget() {
        return new Widget();
    }

    /**
     * Create an instance of {@link WidgetPosition }
     * 
     */
    public WidgetPosition createWidgetPosition() {
        return new WidgetPosition();
    }

    /**
     * Create an instance of {@link WidgetGroup }
     * 
     */
    public WidgetGroup createWidgetGroup() {
        return new WidgetGroup();
    }

    /**
     * Create an instance of {@link ColumnsStyles }
     * 
     */
    public ColumnsStyles createColumnsStyles() {
        return new ColumnsStyles();
    }

    /**
     * Create an instance of {@link TransientData }
     * 
     */
    public TransientData createTransientData() {
        return new TransientData();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Connector.OutputParameters }
     * 
     */
    public Connector.OutputParameters createConnectorOutputParameters() {
        return new Connector.OutputParameters();
    }

    /**
     * Create an instance of {@link Connector }
     * 
     */
    public Connector createConnector() {
        return new Connector();
    }

    /**
     * Create an instance of {@link Validators.Validator }
     * 
     */
    public Validators.Validator createValidatorsValidator() {
        return new Validators.Validator();
    }

    /**
     * Create an instance of {@link Dependencies.Dependency }
     * 
     */
    public Dependencies.Dependency createDependenciesDependency() {
        return new Dependencies.Dependency();
    }

    /**
     * Create an instance of {@link HeadingsPositions }
     * 
     */
    public HeadingsPositions createHeadingsPositions() {
        return new HeadingsPositions();
    }

    /**
     * Create an instance of {@link Actions.Action }
     * 
     */
    public Actions.Action createActionsAction() {
        return new Actions.Action();
    }

    /**
     * Create an instance of {@link TransientData.Data }
     * 
     */
    public TransientData.Data createTransientDataData() {
        return new TransientData.Data();
    }

}
