//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.28 at 10:52:32 PM ALMT 
//


package org.processbase.ui.core.bonita.forms;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PageFlow complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PageFlow">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="pages" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="page" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="page-label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="allow-html-in-label" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="page-template" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="widgets" type="{}Widgets"/>
 *                             &lt;element name="page-validators" type="{}Validators" minOccurs="0"/>
 *                             &lt;element name="next-page" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="actions" type="{}Actions" minOccurs="0"/>
 *                           &lt;/all>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="confirmation-template" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="confirmation-message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="redirection-url" type="{}RedirectionURL" minOccurs="0"/>
 *         &lt;element name="transient-data" type="{}TransientData" minOccurs="0"/>
 *         &lt;element name="connectors" type="{}Connectors" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="first-page" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PageFlow", propOrder = {

})
public class PageFlow {

    protected PageFlow.Pages pages;
    @XmlElement(name = "confirmation-template")
    protected String confirmationTemplate;
    @XmlElement(name = "confirmation-message")
    protected String confirmationMessage;
    @XmlElement(name = "redirection-url")
    protected RedirectionURL redirectionUrl;
    @XmlElement(name = "transient-data")
    protected TransientData transientData;
    protected Connectors connectors;
    @XmlAttribute(name = "first-page")
    protected String firstPage;

    /**
     * Gets the value of the pages property.
     * 
     * @return
     *     possible object is
     *     {@link PageFlow.Pages }
     *     
     */
    public PageFlow.Pages getPages() {
        return pages;
    }

    /**
     * Sets the value of the pages property.
     * 
     * @param value
     *     allowed object is
     *     {@link PageFlow.Pages }
     *     
     */
    public void setPages(PageFlow.Pages value) {
        this.pages = value;
    }

    /**
     * Gets the value of the confirmationTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfirmationTemplate() {
        return confirmationTemplate;
    }

    /**
     * Sets the value of the confirmationTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfirmationTemplate(String value) {
        this.confirmationTemplate = value;
    }

    /**
     * Gets the value of the confirmationMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfirmationMessage() {
        return confirmationMessage;
    }

    /**
     * Sets the value of the confirmationMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfirmationMessage(String value) {
        this.confirmationMessage = value;
    }

    /**
     * Gets the value of the redirectionUrl property.
     * 
     * @return
     *     possible object is
     *     {@link RedirectionURL }
     *     
     */
    public RedirectionURL getRedirectionUrl() {
        return redirectionUrl;
    }

    /**
     * Sets the value of the redirectionUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link RedirectionURL }
     *     
     */
    public void setRedirectionUrl(RedirectionURL value) {
        this.redirectionUrl = value;
    }

    /**
     * Gets the value of the transientData property.
     * 
     * @return
     *     possible object is
     *     {@link TransientData }
     *     
     */
    public TransientData getTransientData() {
        return transientData;
    }

    /**
     * Sets the value of the transientData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransientData }
     *     
     */
    public void setTransientData(TransientData value) {
        this.transientData = value;
    }

    /**
     * Gets the value of the connectors property.
     * 
     * @return
     *     possible object is
     *     {@link Connectors }
     *     
     */
    public Connectors getConnectors() {
        return connectors;
    }

    /**
     * Sets the value of the connectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Connectors }
     *     
     */
    public void setConnectors(Connectors value) {
        this.connectors = value;
    }

    /**
     * Gets the value of the firstPage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstPage() {
        return firstPage;
    }

    /**
     * Sets the value of the firstPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstPage(String value) {
        this.firstPage = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="page" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="page-label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="allow-html-in-label" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="page-template" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="widgets" type="{}Widgets"/>
     *                   &lt;element name="page-validators" type="{}Validators" minOccurs="0"/>
     *                   &lt;element name="next-page" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="actions" type="{}Actions" minOccurs="0"/>
     *                 &lt;/all>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pages"
    })
    public static class Pages {

        @XmlElement(name = "page")
        protected List<PageFlow.Pages.Page> pages;

        /**
         * Gets the value of the pages property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pages property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPages().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PageFlow.Pages.Page }
         * 
         * 
         */
        public List<PageFlow.Pages.Page> getPages() {
            if (pages == null) {
                pages = new ArrayList<PageFlow.Pages.Page>();
            }
            return this.pages;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="page-label" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="allow-html-in-label" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="page-template" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="widgets" type="{}Widgets"/>
         *         &lt;element name="page-validators" type="{}Validators" minOccurs="0"/>
         *         &lt;element name="next-page" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="actions" type="{}Actions" minOccurs="0"/>
         *       &lt;/all>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Page {

            @XmlElement(name = "page-label", required = true)
            protected String pageLabel;
            @XmlElement(name = "allow-html-in-label")
            protected Boolean allowHtmlInLabel;
            @XmlElement(name = "page-template")
            protected String pageTemplate;
            @XmlElement(required = true)
            protected Widgets widgets;
            @XmlElement(name = "page-validators")
            protected Validators pageValidators;
            @XmlElement(name = "next-page")
            protected String nextPage;
            protected Actions actions;
            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the pageLabel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPageLabel() {
                return pageLabel;
            }

            /**
             * Sets the value of the pageLabel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPageLabel(String value) {
                this.pageLabel = value;
            }

            /**
             * Gets the value of the allowHtmlInLabel property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isAllowHtmlInLabel() {
                return allowHtmlInLabel;
            }

            /**
             * Sets the value of the allowHtmlInLabel property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setAllowHtmlInLabel(Boolean value) {
                this.allowHtmlInLabel = value;
            }

            /**
             * Gets the value of the pageTemplate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPageTemplate() {
                return pageTemplate;
            }

            /**
             * Sets the value of the pageTemplate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPageTemplate(String value) {
                this.pageTemplate = value;
            }

            /**
             * Gets the value of the widgets property.
             * 
             * @return
             *     possible object is
             *     {@link Widgets }
             *     
             */
            public Widgets getWidgets() {
                return widgets;
            }

            /**
             * Sets the value of the widgets property.
             * 
             * @param value
             *     allowed object is
             *     {@link Widgets }
             *     
             */
            public void setWidgets(Widgets value) {
                this.widgets = value;
            }

            /**
             * Gets the value of the pageValidators property.
             * 
             * @return
             *     possible object is
             *     {@link Validators }
             *     
             */
            public Validators getPageValidators() {
                return pageValidators;
            }

            /**
             * Sets the value of the pageValidators property.
             * 
             * @param value
             *     allowed object is
             *     {@link Validators }
             *     
             */
            public void setPageValidators(Validators value) {
                this.pageValidators = value;
            }

            /**
             * Gets the value of the nextPage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNextPage() {
                return nextPage;
            }

            /**
             * Sets the value of the nextPage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNextPage(String value) {
                this.nextPage = value;
            }

            /**
             * Gets the value of the actions property.
             * 
             * @return
             *     possible object is
             *     {@link Actions }
             *     
             */
            public Actions getActions() {
                return actions;
            }

            /**
             * Sets the value of the actions property.
             * 
             * @param value
             *     allowed object is
             *     {@link Actions }
             *     
             */
            public void setActions(Actions value) {
                this.actions = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }

}
