//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.28 at 10:52:32 PM ALMT 
//


package org.processbase.ui.core.bonita.forms;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Widget complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Widget">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="variable-bound" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="max-length" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="max-height" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="style" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="label-style" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="label-position" type="{}ItemPosition" minOccurs="0"/>
 *         &lt;element name="allow-html-in-label" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="allow-html-in-field" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="mandatory" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="readonly" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="initial-value" type="{}FieldValue" minOccurs="0"/>
 *         &lt;element name="display-format" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="items-style" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="html-attributes" type="{}HTMLAttributes" minOccurs="0"/>
 *         &lt;element name="available-values" type="{}AvailableValues" minOccurs="0"/>
 *         &lt;element name="validators" type="{}Validators" minOccurs="0"/>
 *         &lt;element name="label-button" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="max-items" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="multi-instantiated" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="max-instances" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="min-instances" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="add-label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="add-label-style" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="add-title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="remove-label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="remove-label-style" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="remove-title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="display-attachment-image" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="image-style" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="table-style" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cell-style" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="headings-style" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="headings-positions" type="{}HeadingsPositions" minOccurs="0"/>
 *         &lt;element name="horizontal-header" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vertical-header" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="select-mode" type="{}SelectMode" minOccurs="0"/>
 *         &lt;element name="selected-items-style" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="value-column-index" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="max-rows" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="min-rows" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="max-columns" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="min-columns" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="variable-columns" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="variable-rows" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="dependencies" type="{}Dependencies" minOccurs="0"/>
 *         &lt;element name="display-after-event" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="value-after-event" type="{}FieldValue" minOccurs="0"/>
 *         &lt;element name="available-values-after-event" type="{}AvailableValues" minOccurs="0"/>
 *         &lt;element name="widget-position" type="{}WidgetPosition" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required" type="{}WidgetType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Widget", propOrder = {

})
public class Widget {

    @XmlElement(name = "variable-bound")
    protected String variableBound;
    protected String title;
    @XmlElement(name = "max-length")
    protected BigInteger maxLength;
    @XmlElement(name = "max-height")
    protected BigInteger maxHeight;
    protected String style;
    protected String label;
    @XmlElement(name = "label-style")
    protected String labelStyle;
    @XmlElement(name = "label-position")
    protected ItemPosition labelPosition;
    @XmlElement(name = "allow-html-in-label")
    protected Boolean allowHtmlInLabel;
    @XmlElement(name = "allow-html-in-field")
    protected Boolean allowHtmlInField;
    protected Boolean mandatory;
    protected Boolean readonly;
    @XmlElement(name = "initial-value")
    protected FieldValue initialValue;
    @XmlElement(name = "display-format")
    protected String displayFormat;
    @XmlElement(name = "items-style")
    protected String itemsStyle;
    @XmlElement(name = "html-attributes")
    protected HTMLAttributes htmlAttributes;
    @XmlElement(name = "available-values")
    protected AvailableValues availableValues;
    protected Validators validators;
    @XmlElement(name = "label-button")
    protected Boolean labelButton;
    @XmlElement(name = "max-items")
    protected BigInteger maxItems;
    @XmlElement(name = "multi-instantiated")
    protected Boolean multiInstantiated;
    @XmlElement(name = "max-instances")
    protected String maxInstances;
    @XmlElement(name = "min-instances")
    protected String minInstances;
    @XmlElement(name = "add-label")
    protected String addLabel;
    @XmlElement(name = "add-label-style")
    protected String addLabelStyle;
    @XmlElement(name = "add-title")
    protected String addTitle;
    @XmlElement(name = "remove-label")
    protected String removeLabel;
    @XmlElement(name = "remove-label-style")
    protected String removeLabelStyle;
    @XmlElement(name = "remove-title")
    protected String removeTitle;
    @XmlElement(name = "display-attachment-image")
    protected Boolean displayAttachmentImage;
    @XmlElement(name = "image-style")
    protected String imageStyle;
    @XmlElement(name = "table-style")
    protected String tableStyle;
    @XmlElement(name = "cell-style")
    protected String cellStyle;
    @XmlElement(name = "headings-style")
    protected String headingsStyle;
    @XmlElement(name = "headings-positions")
    protected HeadingsPositions headingsPositions;
    @XmlElement(name = "horizontal-header")
    protected String horizontalHeader;
    @XmlElement(name = "vertical-header")
    protected String verticalHeader;
    @XmlElement(name = "select-mode")
    protected SelectMode selectMode;
    @XmlElement(name = "selected-items-style")
    protected String selectedItemsStyle;
    @XmlElement(name = "value-column-index")
    protected String valueColumnIndex;
    @XmlElement(name = "max-rows")
    protected String maxRows;
    @XmlElement(name = "min-rows")
    protected String minRows;
    @XmlElement(name = "max-columns")
    protected String maxColumns;
    @XmlElement(name = "min-columns")
    protected String minColumns;
    @XmlElement(name = "variable-columns")
    protected Boolean variableColumns;
    @XmlElement(name = "variable-rows")
    protected Boolean variableRows;
    protected Dependencies dependencies;
    @XmlElement(name = "display-after-event")
    protected Boolean displayAfterEvent;
    @XmlElement(name = "value-after-event")
    protected FieldValue valueAfterEvent;
    @XmlElement(name = "available-values-after-event")
    protected AvailableValues availableValuesAfterEvent;
    @XmlElement(name = "widget-position")
    protected WidgetPosition widgetPosition;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "type", required = true)
    protected WidgetType type;

    /**
     * Gets the value of the variableBound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariableBound() {
        return variableBound;
    }

    /**
     * Sets the value of the variableBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariableBound(String value) {
        this.variableBound = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the maxLength property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxLength() {
        return maxLength;
    }

    /**
     * Sets the value of the maxLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxLength(BigInteger value) {
        this.maxLength = value;
    }

    /**
     * Gets the value of the maxHeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxHeight() {
        return maxHeight;
    }

    /**
     * Sets the value of the maxHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxHeight(BigInteger value) {
        this.maxHeight = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the labelStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelStyle() {
        return labelStyle;
    }

    /**
     * Sets the value of the labelStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelStyle(String value) {
        this.labelStyle = value;
    }

    /**
     * Gets the value of the labelPosition property.
     * 
     * @return
     *     possible object is
     *     {@link ItemPosition }
     *     
     */
    public ItemPosition getLabelPosition() {
        return labelPosition;
    }

    /**
     * Sets the value of the labelPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemPosition }
     *     
     */
    public void setLabelPosition(ItemPosition value) {
        this.labelPosition = value;
    }

    /**
     * Gets the value of the allowHtmlInLabel property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowHtmlInLabel() {
        return allowHtmlInLabel;
    }

    /**
     * Sets the value of the allowHtmlInLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowHtmlInLabel(Boolean value) {
        this.allowHtmlInLabel = value;
    }

    /**
     * Gets the value of the allowHtmlInField property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowHtmlInField() {
        return allowHtmlInField;
    }

    /**
     * Sets the value of the allowHtmlInField property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowHtmlInField(Boolean value) {
        this.allowHtmlInField = value;
    }

    /**
     * Gets the value of the mandatory property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMandatory() {
        return mandatory;
    }

    /**
     * Sets the value of the mandatory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMandatory(Boolean value) {
        this.mandatory = value;
    }

    /**
     * Gets the value of the readonly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReadonly() {
        return readonly;
    }

    /**
     * Sets the value of the readonly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReadonly(Boolean value) {
        this.readonly = value;
    }

    /**
     * Gets the value of the initialValue property.
     * 
     * @return
     *     possible object is
     *     {@link FieldValue }
     *     
     */
    public FieldValue getInitialValue() {
        return initialValue;
    }

    /**
     * Sets the value of the initialValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldValue }
     *     
     */
    public void setInitialValue(FieldValue value) {
        this.initialValue = value;
    }

    /**
     * Gets the value of the displayFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayFormat() {
        return displayFormat;
    }

    /**
     * Sets the value of the displayFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayFormat(String value) {
        this.displayFormat = value;
    }

    /**
     * Gets the value of the itemsStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemsStyle() {
        return itemsStyle;
    }

    /**
     * Sets the value of the itemsStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemsStyle(String value) {
        this.itemsStyle = value;
    }

    /**
     * Gets the value of the htmlAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link HTMLAttributes }
     *     
     */
    public HTMLAttributes getHtmlAttributes() {
        return htmlAttributes;
    }

    /**
     * Sets the value of the htmlAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link HTMLAttributes }
     *     
     */
    public void setHtmlAttributes(HTMLAttributes value) {
        this.htmlAttributes = value;
    }

    /**
     * Gets the value of the availableValues property.
     * 
     * @return
     *     possible object is
     *     {@link AvailableValues }
     *     
     */
    public AvailableValues getAvailableValues() {
        return availableValues;
    }

    /**
     * Sets the value of the availableValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailableValues }
     *     
     */
    public void setAvailableValues(AvailableValues value) {
        this.availableValues = value;
    }

    /**
     * Gets the value of the validators property.
     * 
     * @return
     *     possible object is
     *     {@link Validators }
     *     
     */
    public Validators getValidators() {
        return validators;
    }

    /**
     * Sets the value of the validators property.
     * 
     * @param value
     *     allowed object is
     *     {@link Validators }
     *     
     */
    public void setValidators(Validators value) {
        this.validators = value;
    }

    /**
     * Gets the value of the labelButton property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLabelButton() {
        return labelButton;
    }

    /**
     * Sets the value of the labelButton property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLabelButton(Boolean value) {
        this.labelButton = value;
    }

    /**
     * Gets the value of the maxItems property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxItems() {
        return maxItems;
    }

    /**
     * Sets the value of the maxItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxItems(BigInteger value) {
        this.maxItems = value;
    }

    /**
     * Gets the value of the multiInstantiated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMultiInstantiated() {
        return multiInstantiated;
    }

    /**
     * Sets the value of the multiInstantiated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMultiInstantiated(Boolean value) {
        this.multiInstantiated = value;
    }

    /**
     * Gets the value of the maxInstances property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxInstances() {
        return maxInstances;
    }

    /**
     * Sets the value of the maxInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxInstances(String value) {
        this.maxInstances = value;
    }

    /**
     * Gets the value of the minInstances property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinInstances() {
        return minInstances;
    }

    /**
     * Sets the value of the minInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinInstances(String value) {
        this.minInstances = value;
    }

    /**
     * Gets the value of the addLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddLabel() {
        return addLabel;
    }

    /**
     * Sets the value of the addLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddLabel(String value) {
        this.addLabel = value;
    }

    /**
     * Gets the value of the addLabelStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddLabelStyle() {
        return addLabelStyle;
    }

    /**
     * Sets the value of the addLabelStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddLabelStyle(String value) {
        this.addLabelStyle = value;
    }

    /**
     * Gets the value of the addTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddTitle() {
        return addTitle;
    }

    /**
     * Sets the value of the addTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddTitle(String value) {
        this.addTitle = value;
    }

    /**
     * Gets the value of the removeLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoveLabel() {
        return removeLabel;
    }

    /**
     * Sets the value of the removeLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoveLabel(String value) {
        this.removeLabel = value;
    }

    /**
     * Gets the value of the removeLabelStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoveLabelStyle() {
        return removeLabelStyle;
    }

    /**
     * Sets the value of the removeLabelStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoveLabelStyle(String value) {
        this.removeLabelStyle = value;
    }

    /**
     * Gets the value of the removeTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoveTitle() {
        return removeTitle;
    }

    /**
     * Sets the value of the removeTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoveTitle(String value) {
        this.removeTitle = value;
    }

    /**
     * Gets the value of the displayAttachmentImage property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisplayAttachmentImage() {
        return displayAttachmentImage;
    }

    /**
     * Sets the value of the displayAttachmentImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisplayAttachmentImage(Boolean value) {
        this.displayAttachmentImage = value;
    }

    /**
     * Gets the value of the imageStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageStyle() {
        return imageStyle;
    }

    /**
     * Sets the value of the imageStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageStyle(String value) {
        this.imageStyle = value;
    }

    /**
     * Gets the value of the tableStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableStyle() {
        return tableStyle;
    }

    /**
     * Sets the value of the tableStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableStyle(String value) {
        this.tableStyle = value;
    }

    /**
     * Gets the value of the cellStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCellStyle() {
        return cellStyle;
    }

    /**
     * Sets the value of the cellStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCellStyle(String value) {
        this.cellStyle = value;
    }

    /**
     * Gets the value of the headingsStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeadingsStyle() {
        return headingsStyle;
    }

    /**
     * Sets the value of the headingsStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeadingsStyle(String value) {
        this.headingsStyle = value;
    }

    /**
     * Gets the value of the headingsPositions property.
     * 
     * @return
     *     possible object is
     *     {@link HeadingsPositions }
     *     
     */
    public HeadingsPositions getHeadingsPositions() {
        return headingsPositions;
    }

    /**
     * Sets the value of the headingsPositions property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeadingsPositions }
     *     
     */
    public void setHeadingsPositions(HeadingsPositions value) {
        this.headingsPositions = value;
    }

    /**
     * Gets the value of the horizontalHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHorizontalHeader() {
        return horizontalHeader;
    }

    /**
     * Sets the value of the horizontalHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHorizontalHeader(String value) {
        this.horizontalHeader = value;
    }

    /**
     * Gets the value of the verticalHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerticalHeader() {
        return verticalHeader;
    }

    /**
     * Sets the value of the verticalHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerticalHeader(String value) {
        this.verticalHeader = value;
    }

    /**
     * Gets the value of the selectMode property.
     * 
     * @return
     *     possible object is
     *     {@link SelectMode }
     *     
     */
    public SelectMode getSelectMode() {
        return selectMode;
    }

    /**
     * Sets the value of the selectMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectMode }
     *     
     */
    public void setSelectMode(SelectMode value) {
        this.selectMode = value;
    }

    /**
     * Gets the value of the selectedItemsStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectedItemsStyle() {
        return selectedItemsStyle;
    }

    /**
     * Sets the value of the selectedItemsStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectedItemsStyle(String value) {
        this.selectedItemsStyle = value;
    }

    /**
     * Gets the value of the valueColumnIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueColumnIndex() {
        return valueColumnIndex;
    }

    /**
     * Sets the value of the valueColumnIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueColumnIndex(String value) {
        this.valueColumnIndex = value;
    }

    /**
     * Gets the value of the maxRows property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxRows() {
        return maxRows;
    }

    /**
     * Sets the value of the maxRows property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxRows(String value) {
        this.maxRows = value;
    }

    /**
     * Gets the value of the minRows property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinRows() {
        return minRows;
    }

    /**
     * Sets the value of the minRows property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinRows(String value) {
        this.minRows = value;
    }

    /**
     * Gets the value of the maxColumns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxColumns() {
        return maxColumns;
    }

    /**
     * Sets the value of the maxColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxColumns(String value) {
        this.maxColumns = value;
    }

    /**
     * Gets the value of the minColumns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinColumns() {
        return minColumns;
    }

    /**
     * Sets the value of the minColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinColumns(String value) {
        this.minColumns = value;
    }

    /**
     * Gets the value of the variableColumns property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVariableColumns() {
        return variableColumns;
    }

    /**
     * Sets the value of the variableColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVariableColumns(Boolean value) {
        this.variableColumns = value;
    }

    /**
     * Gets the value of the variableRows property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVariableRows() {
        return variableRows;
    }

    /**
     * Sets the value of the variableRows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVariableRows(Boolean value) {
        this.variableRows = value;
    }

    /**
     * Gets the value of the dependencies property.
     * 
     * @return
     *     possible object is
     *     {@link Dependencies }
     *     
     */
    public Dependencies getDependencies() {
        return dependencies;
    }

    /**
     * Sets the value of the dependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dependencies }
     *     
     */
    public void setDependencies(Dependencies value) {
        this.dependencies = value;
    }

    /**
     * Gets the value of the displayAfterEvent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisplayAfterEvent() {
        return displayAfterEvent;
    }

    /**
     * Sets the value of the displayAfterEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisplayAfterEvent(Boolean value) {
        this.displayAfterEvent = value;
    }

    /**
     * Gets the value of the valueAfterEvent property.
     * 
     * @return
     *     possible object is
     *     {@link FieldValue }
     *     
     */
    public FieldValue getValueAfterEvent() {
        return valueAfterEvent;
    }

    /**
     * Sets the value of the valueAfterEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldValue }
     *     
     */
    public void setValueAfterEvent(FieldValue value) {
        this.valueAfterEvent = value;
    }

    /**
     * Gets the value of the availableValuesAfterEvent property.
     * 
     * @return
     *     possible object is
     *     {@link AvailableValues }
     *     
     */
    public AvailableValues getAvailableValuesAfterEvent() {
        return availableValuesAfterEvent;
    }

    /**
     * Sets the value of the availableValuesAfterEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailableValues }
     *     
     */
    public void setAvailableValuesAfterEvent(AvailableValues value) {
        this.availableValuesAfterEvent = value;
    }

    /**
     * Gets the value of the widgetPosition property.
     * 
     * @return
     *     possible object is
     *     {@link WidgetPosition }
     *     
     */
    public WidgetPosition getWidgetPosition() {
        return widgetPosition;
    }

    /**
     * Sets the value of the widgetPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link WidgetPosition }
     *     
     */
    public void setWidgetPosition(WidgetPosition value) {
        this.widgetPosition = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link WidgetType }
     *     
     */
    public WidgetType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link WidgetType }
     *     
     */
    public void setType(WidgetType value) {
        this.type = value;
    }

}
