/**
 * Copyright (C) 2010 PROCESSBASE Ltd.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2.0 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.processbase.util.db;
// Generated 13.12.2009 22:19:20 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PbSection generated by hbm2java
 */
@Entity
@Table(name="PB_SECTION"
    , uniqueConstraints = @UniqueConstraint(columnNames={"SECTION_NAME", "SECTION_DESC"})
)
public class PbSection  implements java.io.Serializable {


     private long id;
     private String sectionName;
     private String sectionDesc;

    public PbSection() {
    }

	
    public PbSection(String sectionName, String sectionDesc) {
        this.sectionName = sectionName;
        this.sectionDesc = sectionDesc;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, precision=16, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="SECTION_NAME", nullable=false, length=1000)
    public String getSectionName() {
        return this.sectionName;
    }
    
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }
    
    @Column(name="SECTION_DESC", nullable=false, length=1000)
    public String getSectionDesc() {
        return this.sectionDesc;
    }
    
    public void setSectionDesc(String sectionDesc) {
        this.sectionDesc = sectionDesc;
    }

}


