package org.processbase.bam.message;
// Generated 26.02.2010 12:01:04 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.List;

/**
 * PbEvent generated by hbm2java
 */
public class KPIMessage implements java.io.Serializable {

    private long id;
    private String eventId;
    private Date timeStamp;
    private String serverId;
    private String processDefinitionId;
    private String processInstanceId;
    private String processName;
    private String activityDefinitionId;
    private String activityInstanceId;
    private String activityInstanceIter;
    private String activityName;
    private String currentState;
    private Object factValue;
    private String kpiCode;
    private String kpiName;
    private List<List<Object>> dimensions;

    public KPIMessage() {
    }

    public KPIMessage(String eventId, Date timeStamp, String serverId, String processInstanceId, String activityInstanceId, String currentState, String kpiCode, List<List<Object>> dimensions) {
        this.eventId = eventId;
        this.timeStamp = timeStamp;
        this.serverId = serverId;
        this.processInstanceId = processInstanceId;
        this.activityInstanceId = activityInstanceId;
        this.currentState = currentState;
        this.kpiCode = kpiCode;
        this.dimensions = dimensions;
    }

    public KPIMessage(long id, String eventId, Date timeStamp, String serverId, String processDefinitionId, String processInstanceId, String processName, String activityDefinitionId, String activityInstanceId, String activityInstanceIter, String activityName, String currentState, Object factValue, String kpiCode, String kpiName) {
        this.id = id;
        this.eventId = eventId;
        this.timeStamp = timeStamp;
        this.serverId = serverId;
        this.processDefinitionId = processDefinitionId;
        this.processInstanceId = processInstanceId;
        this.processName = processName;
        this.activityDefinitionId = activityDefinitionId;
        this.activityInstanceId = activityInstanceId;
        this.activityInstanceIter = activityInstanceIter;
        this.activityName = activityName;
        this.currentState = currentState;
        this.factValue = factValue;
        this.kpiCode = kpiCode;
        this.kpiName = kpiName;

    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getEventId() {
        return this.eventId;
    }

    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    public Date getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    public String getServerId() {
        return this.serverId;
    }

    public void setServerId(String serverId) {
        this.serverId = serverId;
    }

    public String getProcessDefinitionId() {
        return this.processDefinitionId;
    }

    public void setProcessDefinitionId(String processDefinitionId) {
        this.processDefinitionId = processDefinitionId;
    }

    public String getProcessInstanceId() {
        return this.processInstanceId;
    }

    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    public String getProcessName() {
        return this.processName;
    }

    public void setProcessName(String processName) {
        this.processName = processName;
    }

    public String getActivityDefinitionId() {
        return this.activityDefinitionId;
    }

    public void setActivityDefinitionId(String activityDefinitionId) {
        this.activityDefinitionId = activityDefinitionId;
    }

    public String getActivityInstanceId() {
        return this.activityInstanceId;
    }

    public void setActivityInstanceId(String activityInstanceId) {
        this.activityInstanceId = activityInstanceId;
    }

    public String getActivityInstanceIter() {
        return this.activityInstanceIter;
    }

    public void setActivityInstanceIter(String activityInstanceIter) {
        this.activityInstanceIter = activityInstanceIter;
    }

    public String getActivityName() {
        return this.activityName;
    }

    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }

    public String getCurrentState() {
        return this.currentState;
    }

    public void setCurrentState(String currentState) {
        this.currentState = currentState;
    }

    public Object getFactValue() {
        return factValue;
    }

    public void setFactValue(Object factValue) {
        this.factValue = factValue;
    }

    public String getKpiCode() {
        return this.kpiCode;
    }

    public void setKpiCode(String kpiCode) {
        this.kpiCode = kpiCode;
    }

    public String getKpiName() {
        return this.kpiName;
    }

    public void setKpiName(String kpiName) {
        this.kpiName = kpiName;
    }

    public List<List<Object>> getDimensions() {
        return dimensions;
    }

    public void setDimensions(List<List<Object>> dimensions) {
        this.dimensions = dimensions;
    }
}


