package org.processbase.util.db;
// Generated 13.12.2009 22:19:20 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PbAttachments generated by hbm2java
 */
@Entity
@Table(name="PB_ATTACHMENTS"
)
public class PbAttachment  implements java.io.Serializable {


     private long id;
     private String customId;
     private String proccessUuid;
     private String activityUuid;
     private String fileName;
     private Long fileSize;
     private String fileMimeType;
     private byte[] fileBody;
     private String fileDesc;
     private String fileType;

    public PbAttachment() {
    }

	
    public PbAttachment(long id) {
        this.id = id;
    }
    public PbAttachment(String customId, String proccessUuid, String activityUuid, String fileName, Long fileSize, String fileMimeType, byte[] fileBody, String fileDesc, String fileType) {
       this.customId = customId;
       this.proccessUuid = proccessUuid;
       this.activityUuid = activityUuid;
       this.fileName = fileName;
       this.fileSize = fileSize;
       this.fileMimeType = fileMimeType;
       this.fileBody = fileBody;
       this.fileDesc = fileDesc;
       this.fileType = fileType;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, precision=16, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="CUSTOM_ID", length=200)
    public String getCustomId() {
        return this.customId;
    }
    
    public void setCustomId(String customId) {
        this.customId = customId;
    }
    
    @Column(name="PROCCESS_UUID", length=200)
    public String getProccessUuid() {
        return this.proccessUuid;
    }
    
    public void setProccessUuid(String proccessUuid) {
        this.proccessUuid = proccessUuid;
    }
    
    @Column(name="ACTIVITY_UUID", length=200)
    public String getActivityUuid() {
        return this.activityUuid;
    }
    
    public void setActivityUuid(String activityUuid) {
        this.activityUuid = activityUuid;
    }
    
    @Column(name="FILE_NAME", length=1000)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    @Column(name="FILE_SIZE", precision=10, scale=0)
    public Long getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }
    
    @Column(name="FILE_MIME_TYPE", length=200)
    public String getFileMimeType() {
        return this.fileMimeType;
    }
    
    public void setFileMimeType(String fileMimeType) {
        this.fileMimeType = fileMimeType;
    }
    
    @Column(name="FILE_BODY")
    public byte[] getFileBody() {
        return this.fileBody;
    }
    
    public void setFileBody(byte[] fileBody) {
        this.fileBody = fileBody;
    }
    
    @Column(name="FILE_DESC", length=1000)
    public String getFileDesc() {
        return this.fileDesc;
    }
    
    public void setFileDesc(String fileDesc) {
        this.fileDesc = fileDesc;
    }
    
    @Column(name="FILE_TYPE", length=1000)
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }




}


