package org.processbase.util.db;
// Generated 13.12.2009 22:19:20 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PbDashboards generated by hbm2java
 */
@Entity
@Table(name = "PB_DASHBOARDS", uniqueConstraints = @UniqueConstraint(columnNames = {"DASHBOARD_NAME", "DASHBOARD_DESC"}))
public class PbDashboard implements java.io.Serializable {

    private long id;
    private PbSection pbSection;
    private String dashboardName;
    private String dashboardDesc;

    public PbDashboard() {
    }

    public PbDashboard(String dashboardName, String dashboardDesc) {
        this.dashboardName = dashboardName;
        this.dashboardDesc = dashboardDesc;
    }

    public PbDashboard(PbSection pbSection, String dashboardName, String dashboardDesc) {
        this.pbSection = pbSection;
        this.dashboardName = dashboardName;
        this.dashboardDesc = dashboardDesc;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "SECTION_ID")
    public PbSection getPbSection() {
        return this.pbSection;
    }

    public void setPbSection(PbSection pbSection) {
        this.pbSection = pbSection;
    }

    @Column(name = "DASHBOARD_NAME", nullable = false, length = 1000)
    public String getDashboardName() {
        return this.dashboardName;
    }

    public void setDashboardName(String dashboardName) {
        this.dashboardName = dashboardName;
    }

    @Column(name = "DASHBOARD_DESC", nullable = false, length = 1000)
    public String getDashboardDesc() {
        return this.dashboardDesc;
    }

    public void setDashboardDesc(String dashboardDesc) {
        this.dashboardDesc = dashboardDesc;
    }
}


