package org.processbase.util.db;
// Generated 13.12.2009 22:19:20 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PbDashboardAcl generated by hbm2java
 */
@Entity
@Table(name="PB_DASHBOARD_ACL"
    , uniqueConstraints = @UniqueConstraint(columnNames={"DASHBOARD_ID", "GROUP_DN"}) 
)
public class PbDashboardAcl  implements java.io.Serializable {


     private long id;
     private long dashboardId;
     private String groupDn;

    public PbDashboardAcl() {
    }

    public PbDashboardAcl(long dashboardId, String groupDn) {
       this.dashboardId = dashboardId;
       this.groupDn = groupDn;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, precision=16, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="DASHBOARD_ID", nullable=false, precision=16, scale=0)
    public long getDashboardId() {
        return this.dashboardId;
    }
    
    public void setDashboardId(long dashboardId) {
        this.dashboardId = dashboardId;
    }
    
    @Column(name="GROUP_DN", nullable=false, length=1000)
    public String getGroupDn() {
        return this.groupDn;
    }
    
    public void setGroupDn(String groupDn) {
        this.groupDn = groupDn;
    }




}


