package org.processbase.util.db;
// Generated 13.12.2009 22:19:20 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PbForms generated by hbm2java
 */
@Entity
@Table(name = "PB_FORMS", uniqueConstraints = @UniqueConstraint(columnNames = {"FORM_NAME", "FORM_DESC"}))
public class PbForm implements java.io.Serializable {

    private long id;
    private PbSection pbSection;
    private String formName;
    private String formDesc;
    private String formClassName;

    public PbForm() {
    }

    public PbForm(PbSection pbSection, String formName, String formDesc, String formClassName) {
        this.pbSection= pbSection;
        this.formName = formName;
        this.formDesc = formDesc;
        this.formClassName = formClassName;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "SECTION_ID", nullable = false)
    public PbSection getPbSection() {
        return this.pbSection;
    }

    public void setPbSection(PbSection pbSection) {
        this.pbSection= pbSection;
    }

    @Column(name = "FORM_NAME", nullable = false, length = 1000)
    public String getFormName() {
        return this.formName;
    }

    public void setFormName(String formName) {
        this.formName = formName;
    }

    @Column(name = "FORM_DESC", nullable = false, length = 1000)
    public String getFormDesc() {
        return this.formDesc;
    }

    public void setFormDesc(String formDesc) {
        this.formDesc = formDesc;
    }

    @Column(name = "FORM_CLASS_NAME", nullable = false, length = 1000)
    public String getFormClassName() {
        return this.formClassName;
    }

    public void setFormClassName(String formClassName) {
        this.formClassName = formClassName;
    }
}


