package org.processbase.util.db;
// Generated 04.11.2009 15:36:07 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PbHelp generated by hbm2java
 */
@Entity
@Table(name = "PB_HELP")
public class PbHelp implements java.io.Serializable {

    private String id;
    private String uniqueUuid;
    private byte[] topText;
    private byte[] blueText;
    private byte[] blackText;
    private String fileName;
    private Long fileSize;
    private String fileMimeType;
    private byte[] fileBody;

    public PbHelp() {
    }

    public PbHelp(String id) {
        this.id = id;
    }

    public PbHelp(String id, String uniqueUuid, byte[] topText, byte[] blueText, byte[] blackText, String fileName, Long fileSize, String fileMimeType, byte[] fileBody) {
        this.id = id;
        this.uniqueUuid = uniqueUuid;
        this.topText = topText;
        this.blueText = blueText;
        this.blackText = blackText;
        this.fileName = fileName;
        this.fileSize = fileSize;
        this.fileMimeType = fileMimeType;
        this.fileBody = fileBody;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, length = 100)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "UNIQUE_UUID", length = 2000)
    public String getUniqueUuid() {
        return this.uniqueUuid;
    }

    public void setUniqueUuid(String uniqueUuid) {
        this.uniqueUuid = uniqueUuid;
    }

    @Column(name = "TOP_TEXT")
    public byte[] getTopText() {
        return this.topText;
    }

    public void setTopText(byte[] topText) {
        this.topText = topText;
    }

    @Column(name = "BLUE_TEXT")
    public byte[] getBlueText() {
        return this.blueText;
    }

    public void setBlueText(byte[] blueText) {
        this.blueText = blueText;
    }

    @Column(name = "BLACK_TEXT")
    public byte[] getBlackText() {
        return this.blackText;
    }

    public void setBlackText(byte[] blackText) {
        this.blackText = blackText;
    }

    @Column(name = "FILE_NAME", length = 2000)
    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    @Column(name = "FILE_SIZE", precision = 10, scale = 0)
    public Long getFileSize() {
        return this.fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    @Column(name = "FILE_MIME_TYPE", length = 2000)
    public String getFileMimeType() {
        return this.fileMimeType;
    }

    public void setFileMimeType(String fileMimeType) {
        this.fileMimeType = fileMimeType;
    }

    @Column(name = "FILE_BODY")
    public byte[] getFileBody() {
        return this.fileBody;
    }

    public void setFileBody(byte[] fileBody) {
        this.fileBody = fileBody;
    }
}


