package org.processbase.util.db;
// Generated 12.11.2009 11:45:18 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PbObject generated by hbm2java
 */
@Entity
@Table(name = "PB_OBJECTS")
public class PbObject implements java.io.Serializable {

    private String id;
    private String proccessUuid;
    private String activityUuid;
    private String className;
    private String varName;
    private byte[] objectBody;

    public PbObject() {
    }

    public PbObject(String id) {
        this.id = id;
    }

    public PbObject(String id, String proccessUuid, String activityUuid, String varName, String className, byte[] objectBody) {
        this.id = id;
        this.proccessUuid = proccessUuid;
        this.activityUuid = activityUuid;
        this.className = className;
        this.varName = varName;
        this.objectBody = objectBody;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, length = 100)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "PROCCESS_UUID", length = 2000)
    public String getProccessUuid() {
        return this.proccessUuid;
    }

    public void setProccessUuid(String proccessUuid) {
        this.proccessUuid = proccessUuid;
    }

    @Column(name = "ACTIVITY_UUID", length = 2000)
    public String getActivityUuid() {
        return this.activityUuid;
    }

    public void setActivityUuid(String activityUuid) {
        this.activityUuid = activityUuid;
    }

    @Column(name = "CLASS_NAME", length = 2000)
    public String getClassName() {
        return this.className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    @Column(name = "OBJECT_BODY")
    public byte[] getObjectBody() {
        return this.objectBody;
    }

    public void setObjectBody(byte[] objectBody) {
        this.objectBody = objectBody;
    }

    @Column(name = "VAR_NAME")
    public String getVarName() {
        return varName;
    }

    public void setVarName(String varName) {
        this.varName = varName;
    }

    
}


