package org.processbase.util.db;
// Generated 13.12.2009 22:19:20 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PbObjects generated by hbm2java
 */
@Entity
@Table(name = "PB_OBJECTS")
public class PbObject implements java.io.Serializable {

    private long id;
    private String proccessUuid;
    private String activityUuid;
    private String className;
    private byte[] objectBody;
    private String varName;

    public PbObject() {
    }

    public PbObject(long id) {
        this.id = id;
    }

    public PbObject(String proccessUuid, String activityUuid, String varName, String className, byte[] objectBody) {
        this.proccessUuid = proccessUuid;
        this.activityUuid = activityUuid;
        this.className = className;
        this.objectBody = objectBody;
        this.varName = varName;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "PROCCESS_UUID", length = 200)
    public String getProccessUuid() {
        return this.proccessUuid;
    }

    public void setProccessUuid(String proccessUuid) {
        this.proccessUuid = proccessUuid;
    }

    @Column(name = "ACTIVITY_UUID", length = 200)
    public String getActivityUuid() {
        return this.activityUuid;
    }

    public void setActivityUuid(String activityUuid) {
        this.activityUuid = activityUuid;
    }

    @Column(name = "CLASS_NAME", length = 200)
    public String getClassName() {
        return this.className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    @Column(name = "OBJECT_BODY")
    public byte[] getObjectBody() {
        return this.objectBody;
    }

    public void setObjectBody(byte[] objectBody) {
        this.objectBody = objectBody;
    }

    @Column(name = "VAR_NAME", length = 200)
    public String getVarName() {
        return this.varName;
    }

    public void setVarName(String varName) {
        this.varName = varName;
    }
}


