package org.processbase.util.db;
// Generated 13.12.2009 22:19:20 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PbProcessSection generated by hbm2java
 */
@Entity
@Table(name="PB_PROCESS_SECTION"
    , uniqueConstraints = @UniqueConstraint(columnNames={"PROCCESS_UUID", "SECTION_ID"})
)
public class PbProcessSection  implements java.io.Serializable {


     private long id;
     private PbSection pbSection;
     private String proccessUuid;

    public PbProcessSection() {
    }

    public PbProcessSection( PbSection pbSection, String proccessUuid) {
       this.pbSection = pbSection;
       this.proccessUuid = proccessUuid;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, precision=16, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SECTION_ID", nullable=false)
    public PbSection getPbSection() {
        return this.pbSection;
    }
    
    public void setPbSection(PbSection pbSection) {
        this.pbSection = pbSection;
    }
    
    @Column(name="PROCCESS_UUID", nullable=false, length=1000)
    public String getProccessUuid() {
        return this.proccessUuid;
    }
    
    public void setProccessUuid(String proccessUuid) {
        this.proccessUuid = proccessUuid;
    }




}


