package org.processbase.bam.db;
// Generated 01.03.2011 14:08:13 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MetaDim generated by hbm2java
 */
@Entity
@Table(name = "META_DIM", uniqueConstraints =
@UniqueConstraint(columnNames = "CODE"))
public class MetaDim implements java.io.Serializable {

    private long id;
    private String code;
    private String name;
    private String valueType;
    private short valueLength;
    private Set<MetaKpi> metaKpis = new HashSet<MetaKpi>(0);

    public MetaDim() {
    }

    public MetaDim(long id, String code, String name, String valueType, short valueLength) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.valueType = valueType;
        this.valueLength = valueLength;
    }

    public MetaDim(long id, String code, String name, String valueType, short valueLength, Set<MetaKpi> metaKpis) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.valueType = valueType;
        this.valueLength = valueLength;
        this.metaKpis = metaKpis;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "CODE", nullable = false, length = 16)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "NAME", nullable = false, length = 200)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "VALUE_TYPE", nullable = false, length = 20)
    public String getValueType() {
        return this.valueType;
    }

    public void setValueType(String valueType) {
        this.valueType = valueType;
    }

    @Column(name = "VALUE_LENGTH", nullable = false, length = 4)
    public short getValueLength() {
        return valueLength;
    }

    public void setValueLength(short valueLength) {
        this.valueLength = valueLength;
    }



    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "META_KPI_DIM", schema = "PBBAM2", joinColumns = {
        @JoinColumn(name = "DIM_ID", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "KPI_ID", nullable = false, updatable = false)})
    public Set<MetaKpi> getMetaKpis() {
        return this.metaKpis;
    }

    public void setMetaKpis(Set<MetaKpi> metaKpis) {
        this.metaKpis = metaKpis;
    }
}
